WITH TRANSACTIONS_BY_DATE AS (
SELECT
    TRANSACTION_DATE,
    SUM(COALESCE(SPEND, 0)) AS SPEND
FROM
    {{ref('scopein_fact_transactions')}} as f
LEFT JOIN (SELECT TXT_CATEGORY_LVL3, TXT_CATEGORY_LVL1 FROM {{ref('scopein_dim_category')}} ) AS b USING(TXT_CATEGORY_LVL3)
WHERE PERSONAL_IBAN = 'DE****3827' AND b.TXT_CATEGORY_LVL1 != 'Income'
GROUP BY 1
ORDER BY 1 ASC
)
SELECT
b.TRANSACTION_YEAR_MONTH_AS_DATE,
b.TRANSACTION_DAY_OF_MONTH,
b.TRANSACTION_DATE,
a.SPEND
FROM
     {{ref('scopein_dim_date')}} as b
LEFT JOIN
     TRANSACTIONS_BY_DATE as a ON b.TRANSACTION_DATE = a.TRANSACTION_DATE
ORDER BY TRANSACTION_DATE ASC
