SELECT
TRANSACTION_YEAR_MONTH_AS_DATE,
TRANSACTION_DAY_OF_MONTH,
TRANSACTION_DATE,
SPEND,
SUM(SPEND) OVER (PARTITION BY TRANSACTION_YEAR_MONTH_AS_DATE ORDER BY TRANSACTION_DAY_OF_MONTH ASC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CUMULATIVE_SPEND_FOR_THE_MONTH
FROM {{ref('scopein_view_mainaccount_transactionsbyday')}}
ORDER BY TRANSACTION_DATE ASC