SELECT
CONCAT(TO_VARCHAR(YEAR(TRANSACTION_DATE)),'-',TO_VARCHAR(MONTH(TRANSACTION_DATE))) AS YEAR_MONTH,
SUM(AMOUNT) AS TOTAL_AMOUNT
FROM
    {{ref('scopeout_review')}}
WHERE SCOPE_OUT = TRUE
GROUP BY 1
ORDER BY 1 ASC