SELECT
	TRANSACTION_ID ,
	TO_DATE(DATE_ENREGISTREMENT)AS DATE_ENREGISTREMENT,
	NAME_PERSONAL_ACCOUNT ,
	TO_DECIMAL(MONTANT) AS MONTANT,
	TO_DECIMAL(SOLDE_COMPTE) AS SOLDE_COMPTE,
	BENEFICIAIRE ,
	TRANSACTION_DESCRIPTION ,
	COALESCE(BENEFICIAIRE_IBAN, BENEFICIAIRE_IBAN2) AS BENEFICIAIRE_IBAN,
	CATEGORIE_L1 ,
	CATEGORIE_L2 ,
    (CONTRAT='ja')::BOOLEAN AS CONTRAT,
	CONTRAT_RECURRENCE ,
	CONTRAT_ID ,
	(TRANSFER='ja')::BOOLEAN AS TRANSFER ,
    (EXCLUS_REVENUS='ja')::BOOLEAN AS EXCLUS_REVENUS,
	TRANSACTION_METHODE ,
	REVENUS_DEPENSES ,
	CONCAT(LEFT(PERSONAL_IBAN,2), '****', RIGHT(PERSONAL_IBAN,4)) AS PERSONAL_IBAN
FROM
    {{source('staging', 'STG_FINANZGURU')}}