SELECT
    a.TRANSACTION_ID ,
	a.DATE_ENREGISTREMENT AS TRANSACTION_DATE,
	a.MONTANT AS TRANSACTION_AMOUNT,
    a.TRANSACTION_DESCRIPTION,
    a.TRANSACTION_METHODE ,
	a.SOLDE_COMPTE AS ACCOUNT_SOLDE,
    a.NAME_PERSONAL_ACCOUNT AS ACCOUNT_FINANZGURU_NAME,
    a.PERSONAL_IBAN AS ACCOUNT_IBAN,
	a.BENEFICIAIRE AS RECEIVER_NAME,
	a.BENEFICIAIRE_IBAN AS RECEIVER_IBAN,
    a.REVENUS_DEPENSES AS FINANZGURU_L0,
	a.CATEGORIE_L1 AS FINANZGURU_L1,
	a.CATEGORIE_L2 AS FINANZGURU_L2,
    a.CONTRAT AS CONTRACT_FLAG,
	a.CONTRAT_RECURRENCE AS CONTRACT_RECURRENCE ,
	a.CONTRAT_ID AS CONTRACT_ID,
	a.TRANSFER AS TRANSFER_FLAG,
    a.EXCLUS_REVENUS AS OUTOFSCOPE_FLAG,
    b.L0 AS CATEGORYTREE_L0,
    b.L1 AS CATEGORYTREE_L1,
    b.L2 AS CATEGORYTREE_L2,
    c.ACCOUNT_NAME AS ACCOUNT_DBT_NAME,
    d.ACCOUNT_NAME AS RECEIVER_ACCOUNT_NAME,
    IS_NULL_VALUE(d.ACCOUNT_NAME) AS RECEIVER_IS_ACCOUNT_FLAG
FROM
    {{ref('formatstage')}} a
LEFT JOIN  {{ ref('categorytree') }} b ON a.CATEGORIE_L2 = b.L2
LEFT JOIN {{ref('accounts')}} c ON a.PERSONAL_IBAN = c.ACCOUNT_IBAN
LEFT JOIN {{ref('accounts')}} d ON CONCAT(LEFT(a.BENEFICIAIRE_IBAN,2), '****', RIGHT(a.BENEFICIAIRE_IBAN,4)) = d.ACCOUNT_IBAN