SELECT
a.TRANSACTION_ID ,
a.TRANSACTION_DATE,
a.NAME_PERSONAL_ACCOUNT ,
a.AMOUNT,
a.ACCOUNT_BALANCE,
a.BENEFICIARY,
a.TRANSACTION_DESCRIPTION ,
a.BENEFICIARY_IBAN,
a.FINANZGURU_CATEGORY_LVL1,
a.FINANZGURU_CATEGORY_LVL2,
a.IS_CONTRACT,
b.RECURRENCE_ENGLISH AS CONTRACT_RECURRENCE,
a.CONTRACT_ID,
a.IS_TRANSFER ,
a.SCOPE_OUT,
c.TRANSACTION_TYPE_ENGLISH AS TRANSACTION_TYPE,
d.INCOME_EXPENSE_ENGLISH AS INCOME_EXPENSE,
a.PERSONAL_IBAN,
a.FILENAME,
a.PROCESSING_DATE,
a.TXT_CATEGORY_LVL3,
a.beneficiary_iban_masked
FROM
{{ref('formatstage')}} a
LEFT JOIN {{ref('recurrence_german_to_english')}} b on a.CONTRACT_RECURRENCE = b.recurrence_german
LEFT JOIN {{ref('transaction_type_german_to_english')}} c on a.TRANSACTION_TYPE = c.TRANSACTION_TYPE_GERMAN
LEFT JOIN {{ref('income_expense_german_to_english')}} d on a.INCOME_EXPENSE = d.INCOME_EXPENSE_GERMAN