SELECT
a.TRANSACTION_ID ,
a.TRANSACTION_DATE,
a.NAME_PERSONAL_ACCOUNT ,
a.AMOUNT,
a.ACCOUNT_BALANCE,
a.TRANSACTION_DESCRIPTION ,
a.BENEFICIARY_IBAN,
a.FINANZGURU_CATEGORY_LVL1,
a.FINANZGURU_CATEGORY_LVL2,
a.IS_CONTRACT,
a.CONTRACT_RECURRENCE,
a.CONTRACT_ID,
a.IS_TRANSFER ,
a.SCOPE_OUT,
a.TRANSACTION_TYPE,
a.INCOME_EXPENSE,
a.PERSONAL_IBAN,
a.FILENAME,
a.PROCESSING_DATE,
a.TXT_CATEGORY_LVL3,
(d.ACCOUNT_NAME IS NOT NULL)::BOOLEAN AS RECEIVER_IS_PERSONAL_ACCOUNT_FLAG,
a.beneficiary_iban_masked,
CASE WHEN RECEIVER_IS_PERSONAL_ACCOUNT_FLAG = TRUE THEN d.ACCOUNT_NAME ELSE a.BENEFICIARY END AS BENEFICIARY
FROM
    {{ref('with_personal_account_name')}} as a
LEFT JOIN {{ref('accounts')}} d ON a.beneficiary_iban_masked = d.ACCOUNT_IBAN