WITH date_spine AS (
SELECT
DATE_DAY AS TRANSACTION_DATE,
DAY(DATE_DAY) AS TRANSACTION_DAY_OF_MONTH,
MONTH(DATE_DAY) AS TRANSACTION_MONTH_OF_YEAR,
YEAR(DATE_DAY) AS TRANSACTION_YEAR,
date_from_parts(YEAR(DATE_DAY), MONTH(DATE_DAY), 1) AS TRANSACTION_YEAR_MONTH_AS_DATE
FROM {{ref('source_dim_date_spine')}}),

date_in_range AS (
SELECT
MIN(TRANSACTION_DATE) AS MIN_DATE,
MAX(TRANSACTION_DATE) AS MAX_DATE
FROM {{ref('formatstage')}} )

SELECT
TRANSACTION_DATE,
TRANSACTION_DAY_OF_MONTH,
TRANSACTION_MONTH_OF_YEAR,
TRANSACTION_YEAR,
TRANSACTION_YEAR_MONTH_AS_DATE
FROM date_spine
WHERE TRANSACTION_DATE > (SELECT MIN_DATE FROM date_in_range)
AND TRANSACTION_DATE < (SELECT MAX_DATE FROM date_in_range)
ORDER BY TRANSACTION_DATE
