SELECT
YEAR_MONTH, INCOME, EXPENSES, SAVINGS, INCOME - EXPENSES - SAVINGS AS BALANCE, INCOME - EXPENSES AS NET_INCOME
FROM {{ref('scopein_view_level1_join')}}
PIVOT(SUM(SPEND) FOR TXT_CATEGORY_LVL1 IN ('Income', 'Expenses', 'Savings')) AS p (YEAR_MONTH, INCOME, EXPENSES, SAVINGS)
ORDER BY YEAR_MONTH ASC
