[project]
name = "stagingfinanzgurutosf"
version = "0.0.1"
description = "A small example package"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]