name: On pull request to main publish to TestPyPI

on:
  pull_request:
    types: [ closed ]
    branches: [main]

jobs:
  on_pull_to_main_publish_to_testpypi:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: run pytest
        env:
          WAREHOUSE: ${{ secrets.SF_DEV_WAREHOUSE }}
          ACCOUNT: ${{ secrets.SF_DEV_ACCOUNT }}
          USER: ${{ secrets.SF_DEV_USER }}
          DATABASE: ${{ secrets.SF_DEV_DATABASE }}
          SCHEMA: ${{ secrets.SF_DEV_SCHEMA }}
          ROLE: ${{ secrets.SF_DEV_ROLE }}
          PASSWORD: ${{ secrets.SF_DEV_PASSWORD }}
        run: |
          python -m pytest
      - name: Build package
        run: python -m build
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_GITHUB_TOKEN}}
          repository-url: https://test.pypi.org/legacy/