name: on_pr_closed_to_master_merge_back_to_qa
on:
  pull_request:
    branches: [master]
    types: [closed]
jobs:
  on_pr_closed_to_master_merge_back_to_qa:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Merge master back to dev
      run: |
          git fetch --unshallow
          git checkout qa
          git pull
          git merge --no-ff master -m "Auto-merge master back to qa"
          git push