name: on_push_run_pytest
# From https://hackernoon.com/how-to-integrate-github-actions-and-cicd-with-your-next-python-project
# https://github.com/horosin/python-standard-ci
# https://www.section.io/engineering-education/setting-up-cicd-for-python-packages-using-github-actions/
on:
  push:
    branches: [main, dev_*, qa*, paul_*]

jobs:
  on_push_run_pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip==23.0.1
        python -m pip install -r requirements.txt
    - name: Pytest
      run: |
        pytest